FROM node:20.11.0-alpine3.19

WORKDIR /app

COPY package.json test_echoserver.ts ./

ADD src ./src

RUN npm install npm@10.3.0 && npm install

ENTRYPOINT ["node", "--import", "tsx", "test_echoserver.ts"]
